import { Permission, PERMISSIONS } from './permission.js';

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  ADMIN: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,

    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,
  ],

  USER: [PERMISSIONS.PROFILE_READ, PERMISSIONS.PROFILE_UPDATE],
};
